../src/riscv/core/riscv/riscv_xilinx_2r1w.v
../src/riscv/core/riscv/riscv_defs.v
../src/riscv/core/riscv/riscv_pipe_ctrl.v
../src/riscv/top_cache_axi/src_v/dcache_core_data_ram.v
../src/usb_host/src_v/usbh_crc5.v
../src/usb_host/src_v/usbh_crc16.v
../src/riscv/top_cache_axi/src_v/dcache_core_tag_ram.v
../src/riscv/core/riscv/riscv_csr_regfile.v
../src/riscv/top_cache_axi/src_v/dcache_axi_axi.v
../src/riscv/core/riscv/riscv_decoder.v
../src/riscv/core/riscv/riscv_alu.v
../src/riscv/core/riscv/riscv_regfile.v
../src/riscv/top_cache_axi/src_v/dcache_core.v
../src/riscv/core/riscv/riscv_exec.v
../src/riscv/core/riscv/riscv_mmu.v
../src/riscv/top_cache_axi/src_v/dcache_pmem_mux.v
../src/riscv/top_cache_axi/src_v/icache_tag_ram.v
../src/usb_host/src_v/usbh_fifo.v
../src/riscv/core/riscv/riscv_lsu.v
../src/riscv/core/riscv/riscv_divider.v
../src/riscv/top_cache_axi/src_v/dcache_axi.v
../src/usb_host/src_v/usbh_sie.v
../src/riscv/top_cache_axi/src_v/dcache_if_pmem.v
../src/riscv/top_cache_axi/src_v/icache_data_ram.v
../src/riscv/core/riscv/riscv_fetch.v
../src/riscv/core/riscv/riscv_decode.v
../src/riscv/core/riscv/riscv_issue.v
../src/riscv/top_cache_axi/src_v/dcache_mux.v
../src/riscv/core/riscv/riscv_multiplier.v
../src/riscv/core/riscv/riscv_csr.v
../src/spiflash/src_v/spi_lite_pmem.v
../src/dbg_bridge/src_v/dbg_bridge_fifo.v
../src/ulpi_wrapper/src_v/ulpi_wrapper.v
../src/core_soc/src_v/axi4lite_dist.v
../src/core_soc/src_v/timer_defs.v
../src/core_soc/src_v/timer.v
../src/core_soc/src_v/gpio_defs.v
../src/core_soc/src_v/gpio.v
../src/riscv/core/riscv/riscv_core.v
../src/core_soc/src_v/irq_ctrl_defs.v
../src/core_soc/src_v/irq_ctrl.v
../src/riscv/top_cache_axi/src_v/icache.v
../src/soc/soc_axi_arb.v
../src/soc/soc_axi_dist.v
../src/core_soc/src_v/uart_lite_defs.v
../src/core_soc/src_v/uart_lite.v
../src/soc/soc_axi_retime.v
../src/usb_host/src_v/usbh_host_defs.v
../src/usb_host/src_v/usbh_host.v
../src/riscv/top_cache_axi/src_v/dcache.v
../src/core_soc/src_v/spi_lite_defs.v
../src/core_soc/src_v/spi_lite.v
../src/dbg_bridge/src_v/dbg_bridge_uart.v
../src/dbg_bridge/src_v/dbg_bridge.v
../src/soc/soc_arb.v
../src/cdc/axi4_cdc.v
../src/spiflash/src_v/spirom.v
../src/usb_host_top/usb_host_top.v
../src/core_soc/src_v/core_soc.v
../src/riscv/top_cache_axi/src_v/riscv_top.v
../src/cdc/axi4_lite_cdc.v
../src/ddr/usb2sniffer_ddr.v
../src/pll/artix7_pll.v
../src/pll/reset_gen.v
../src/soc/fpga_top.v
../src/cdc/axi_cdc_buffer.xci
../src/cdc/axilite_cdc_buffer.xci
../src/ddr/mig_axis.xci
../src/ddr/mig_a.prj
../src/top/usb2sniffer.xdc
../src/top/top.v
